version: '3'
services:
  sksjti-ims:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/opt/www/app/
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
